/* eslint-disable */

declare module 'glob:./sources/{*.ts,**/index.ts}' {
  export const _36kr: typeof import('./sources/_36kr')
  export const _3dm_metacritic: typeof import('./sources/_3dm_metacritic')
  export const _3dm_news: typeof import('./sources/_3dm_news')
  export const baidu: typeof import('./sources/baidu')
  export const bilibili: typeof import('./sources/bilibili')
  export const cankaoxiaoxi: typeof import('./sources/cankaoxiaoxi')
  export const cls: typeof import('./sources/cls/index')
  export const coolapk: typeof import('./sources/coolapk/index')
  export const deconstructoroffun: typeof import('./sources/deconstructoroffun')
  export const douyin: typeof import('./sources/douyin')
  export const famitsu_rank: typeof import('./sources/famitsu_rank')
  export const fastbull: typeof import('./sources/fastbull')
  export const gamebiz: typeof import('./sources/gamebiz')
  export const gamedeveloper: typeof import('./sources/gamedeveloper')
  export const gamesindustry: typeof import('./sources/gamesindustry')
  export const gelonghui: typeof import('./sources/gelonghui')
  export const github: typeof import('./sources/github')
  export const hackernews: typeof import('./sources/hackernews')
  export const indienova_article: typeof import('./sources/indienova_article')
  export const indienova_development: typeof import('./sources/indienova_development')
  export const indienova_recent: typeof import('./sources/indienova_recent')
  export const ithome: typeof import('./sources/ithome')
  export const jin10: typeof import('./sources/jin10')
  export const kaopu: typeof import('./sources/kaopu')
  export const kuaishou: typeof import('./sources/kuaishou')
  export const linuxdo: typeof import('./sources/linuxdo')
  export const newzoo: typeof import('./sources/newzoo')
  export const producthunt: typeof import('./sources/producthunt')
  export const solidot: typeof import('./sources/solidot')
  export const sputniknewscn: typeof import('./sources/sputniknewscn')
  export const thepaper: typeof import('./sources/thepaper')
  export const thisisgame: typeof import('./sources/thisisgame')
  export const tieba: typeof import('./sources/tieba')
  export const toutiao: typeof import('./sources/toutiao')
  export const v2ex: typeof import('./sources/v2ex')
  export const wallstreetcn: typeof import('./sources/wallstreetcn')
  export const weibo: typeof import('./sources/weibo')
  export const xueqiu: typeof import('./sources/xueqiu')
  export const zaobao: typeof import('./sources/zaobao')
  export const zhihu: typeof import('./sources/zhihu')
}
